name: Python Lint & HTML Report

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Flake8 and flake8-html
        run: python -m pip install flake8 flake8-html

      - name: Run Flake8 with HTML report
        run: flake8 . --format=html --htmldir=flake8-report

      - name: Upload Flake8 HTML report
        uses: actions/upload-artifact@v4
        with:
          name: flake8-html-report
          path: flake8-report
